services:
  web:
    build: .
    image: frontend_image
    container_name: frontend_container
    restart: always
    stdin_open: true
    tty: true
    network_mode: bridge
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    volumes:
      - "../env:/home/env"
    ports:
      - "3000:3000"
